<?xml version="1.0"?>
<package format="2">
  <name>qt6_ros_cpp</name>
  <version>0.0.1</version>
  <description>C++ version of the Qt6 ROS1 bridge</description>
  <maintainer email="joao@todo.todo">joao</maintainer>
  <license>GPLv3</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>roslib</build_depend>
  <build_depend>libopencv-dev</build_depend>
  <build_depend>qt6-base-dev</build_depend>
  <build_depend>qt6-declarative-dev</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>roslib</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>roslib</exec_depend>
  <exec_depend>libopencv-dev</exec_depend>
  <exec_depend>qt6-base-dev</exec_depend>
  <exec_depend>qt6-declarative-dev</exec_depend>
</package>
